update celebratins module.
sagarsehrawat/ConceptDash-CRM pull request #38
Opened 2023-08-02 13:56 UTC by Akarshcd

updated a new celebrations module.

2023-08-08 16:15 UTC, Daemon-25 requested changes

2023-08-09 13:06 UTC, Akarshcd commented on src/Components/Dashboards/Celebrations.css
> +    /* identical to box height, or 143% */
done!

2023-08-09 13:07 UTC, Akarshcd commented on src/Components/Dashboards/Celebrations.js
> +// import celebrationActive from "../../Images/Celebrations_Active.svg";
done!

2023-08-09 13:14 UTC, Akarshcd commented on src/Components/Dashboards/Celebrations.js
> +                   console.log(upcomingevents)
done!

2023-08-09 14:13 UTC, Akarshcd commented on src/Components/Dashboards/Home.js
> +      // marginLeft: '113.6px',
done!

2023-08-09 14:13 UTC, Akarshcd commented on src/Components/Dashboards/Home.js
> +      position: "absolute",
have checked, its working fine!

2023-08-09 14:14 UTC, Akarshcd commented on src/Components/Dashboards/Celebrations.js
> +                  console.log(empdata)
done!

2023-08-21 17:58 UTC, Daemon-25 approved these changes

2023-08-21 17:59 UTC, merged